export let bootstrapOptions = {
    version: 5,
    accordionCloseOthers: true,
    accordionGroupPanelClass: '',
    btnLoadingText: 'Loading...',
    dropdownAutoClose: 'always',
    paginationBoundaryLinks: false,
    paginationDirectionLinks: true,
    paginationFirstText: 'First',
    paginationHideSinglePage: true,
    paginationLastText: 'Last',
    paginationNextText: '>',
    paginationPreviousText: '<',
    popoverPosition: 'top',
    popoverTrigger: 'click',
    tabsetType: 'tabs',
    tabsetVertical: false,
    tooltipClass: 'tooltip',
    tooltipPosition: 'top',
    tooltipTrigger: 'hover focus'
};
